# newrelic Exporter Workflow
# This workflow responsible for running newrelic exporter.
# new_relic_api_key: The New Relic API key. To create a User API key, see the <a href="https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys" target="_blank"> New Relic documentation</a>.
# new_relic_account_id: The New Relic account ID. To retrieve the account ID, click the user menu on the lower-left corner of your New Relic dashboard, then go to Administration > Access management > Accounts to see account IDs. For more information on how to find the account ID, see the <a href="https://docs.newrelic.com/docs/accounts/accounts-billing/account-structure/account-id/" target="_blank"> New Relic documentation</a>.
# new_relic_graphql_url: URL for New Relic GraphQL API. If not provided, the default value will be https://api.newrelic.com/graphql. Users in the EU region should use <a href="https://api.eu.newrelic.com/graphql" target="_blank"> https://api.eu.newrelic.com/graphql</a>. For more information on GraphQL URL, see the <a href="https://docs.newrelic.com/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph/" target="_blank"> New Relic documentation</a>.
# new_relic_rest_api_url: Base URL for New Relic REST API. If not provided, the default value will be https://api.newrelic.com. Users in the EU region should use <a href="https://api.eu.newrelic.com" target="_blank"> https://api.eu.newrelic.com</a>. For more information on REST API URL, see the <a href="https://docs.newrelic.com/docs/apis/rest-api-v2/get-started/introduction-new-relic-rest-apis/" target="_blank"> New Relic documentation</a>.
name: New Relic Integration

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'  # Runs every hour

jobs:
  newrelic-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Run New Relic Integration
        run: |
          docker run -i --rm \
            -e OCEAN__EVENT_LISTENER='{"type":"ONCE"}' \
            -e OCEAN__INITIALIZE_PORT_RESOURCES=true \
            -e OCEAN__INTEGRATION__CONFIG__NEW_RELIC_API_KEY=${{ secrets.NEW_RELIC_API_KEY }} \
            -e OCEAN__INTEGRATION__CONFIG__NEW_RELIC_ACCOUNT_ID=${{ secrets.NEW_RELIC_ACCOUNT_ID }} \
            -e OCEAN__PORT__CLIENT_ID=${{ secrets.PORT_CLIENT_ID }} \
            -e OCEAN__PORT__CLIENT_SECRET=${{ secrets.PORT_CLIENT_SECRET }} \
            -e OCEAN__PORT__BASE_URL='https://api.port.io' \
            ghcr.io/port-labs/port-ocean-newrelic:latest

